[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Build settings
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

# Form handling configuration
[forms]
  # Email notifications for form submissions
  [[forms.notifications]]
    to = "dhruvagrawal552@gmail.com"
    from = "noreply@netlify.com"
    subject = "New Portfolio Contact Form Submission"
    body = """
    You have received a new message from your portfolio website:

    Name: {{ name }}
    Email: {{ email }}
    Subject: {{ subject }}

    Message:
    {{ message }}

    ---
    This message was sent from your portfolio contact form.
    """

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "max-age=31536000"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "max-age=31536000"